# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import assignment1_pb2 as assignment1__pb2


class TweetSenderStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SendTweet = channel.unary_stream(
        '/assignment1.TweetSender/SendTweet',
        request_serializer=assignment1__pb2.SizeRequest.SerializeToString,
        response_deserializer=assignment1__pb2.TweetReply.FromString,
        )


class TweetSenderServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SendTweet(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TweetSenderServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SendTweet': grpc.unary_stream_rpc_method_handler(
          servicer.SendTweet,
          request_deserializer=assignment1__pb2.SizeRequest.FromString,
          response_serializer=assignment1__pb2.TweetReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'assignment1.TweetSender', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
